### ISSUE TITLE
[Bug]:ニュースの記事が表示されない 

### ISSUE THREAD

**Issue by sask1978** [Chipppppppppp/LIME#103]
[問題]
LINEのニュースの記事一覧をクリックすると、一瞬記事の内容が表示されるのですが、その後ヤフーの検索ボックスだけが残った空白ページに飛ばされてしまいます。

１枚目のスクリーンショットの記事のリンクをタッチすると
２枚目の画面が0.5秒ほど表示されて、
３枚目の画像になり、記事内容が読めません。

[設定]
「WebViewを既定のブラウザにリダイレクト」と「ブラウザアプリで開く」それぞれ３パターンでオン・オフしてみましたが、同じエラーのままです。

非root・LSPatch済

![Screenshot_1](https://github.com/Chipppppppppp/LIME/assets/166222438/ad87d438-61d5-4d33-8880-7a3d414714da)
![Screenshot_2](https://github.com/Chipppppppppp/LIME/assets/166222438/e249ced9-bf2f-4e92-bb57-427365a44884)
![Screenshot_3](https://github.com/Chipppppppppp/LIME/assets/166222438/187996d9-190e-4ae3-93db-67a0597c9bb2)

**Comment by areteruhiro** [comment]
同じ現象です。
改善できたらpullリクエストしておきますね。
https://github.com/Chipppppppppp/LIME/assets/108941410/b9903723-7182-4777-b070-c843d9b920fe

**Comment by Chipppppppppp** [comment]
ご報告ありがとうございます、Pull Request もありがとうございます... (ここ最近見れていませんでした)

**Comment by areteruhiro** [comment]
4月は忙しいですから、、、
