### ISSUE TITLE
[Feature Request]: グループ退会時の自動メッセージを出さない機能

### ISSUE THREAD

**Issue by yo-ka** [Chipppppppppp/LIME#104]
### 提案内容

自分がLINEのグループを退会した時に、メッセージ欄に「○○がグループを退会しました」という退会時に自動で残されるメッセージを出さずに、
他のグループ参加者には知られず、しれっとグループを抜けられるような機能は難しいでしょうか。

**Comment by areteruhiro** [comment]
根本的な方法ではありませんが。
名前をUNKNOWNにして退出するという方法が一応ありますね。

**Comment by yo-ka** [comment]
非表示にすること自体は無理なんですね。
大勢のグループなら問題ないですが、少人数だとバレますね。
需要はなさそうですが、もし実装が可能であれば検討をお願いします。

**Comment by Chipppppppppp** [comment]
退会のrequestを送ると自動的に送られる場合無理かもしれませんが、試してみればいけるかもですね

**Comment by Chipppppppppp** [comment]
調べましたが原理的に難しそうです。

**Comment by yo-ka** [comment]
わざわざ調べて頂きありがとうございます🙇‍♀️
承知しました。これからも応援しています！
