### ISSUE TITLE
[Feature Request]: keepUnreadの保存

### ISSUE THREAD

**Issue by areteruhiro** [Chipppppppppp/LIME#107]
### 提案内容

keepUnreadのボタンがアプリを開き直すと、無効に戻るので、有効のまま(保存されるように)にしてほしい

**Comment by Chipppppppppp** [comment]
これは無効に戻るほうがいいかと思っていましたが、考え直しています
有効のまま保存するようにするかもしれません

**Comment by Chipppppppppp** [comment]
https://github.com/Chipppppppppp/LIME/commit/36777e3cd58b1ca553f5c149724110adf64e0ea1
忘れていましたが、すでにこちらで対応しています。
