### ISSUE TITLE
line通知アイコンについて[Feature Request]: 

### ISSUE THREAD

**Issue by esperanzality** [Chipppppppppp/LIME#118]
### 提案内容

LINEアイコンの右上の通知マーク(赤丸に未読数)についてです。
通知バーから通知を消すと、アイコンの通知マークも消えてしまうのを消さないようにできないでしょうか。
iPhoneでは通知を消しても、未読メッセージが残っていれば赤丸通知で未読数を確認できるので、同じような使い勝手にしてほしいです。

**Comment by areteruhiro** [comment]
未読数を表示させてるのは、ホームランチャー側の機能ですね。
どの、ほーむランチャーアプリをお使いですか？

**Comment by esperanzality** [comment]
ホームランチャーかどうかは不明ですが、galaxys24です。
ホーム画面のLINEアイコンに右上に表示される赤い通知アイコンの話です。androidの通常機能だと思います。(どんなアプリでも通知アイコンは表示されるはずなので)

また、LSpatch環境では位置情報のmapは使えないでしょうか？

**Comment by s1204IT** [comment]
まず、Issue内では質問を一つにまとめてくだい。  
複数の質問をしないでください。

---
ホーム画面はアプリの一種です。  
未読数カウント機能は**Android標準の機能ではありません**。  
この問題に関しては、LINEアプリ、LIMEモジュールで対応出来る話では無いので無理です。
