### ISSUE TITLE
[Feature Request]: トークの非表示の恒久化

### ISSUE THREAD

**Issue by yousandesu** [Chipppppppppp/LIME#120]
### 提案内容

グループLINEなどで、通知をオフにしてトークを非表示にしていても新しいトークが送信される度にトークの一番上に表示され、また非表示にするという繰り返しが大変です。
(１番上にきているので誤ってタップしてしまうことも...)

そこでトークを非表示にしたら新しいトークが送信されても非表示の状態を維持できる機能が可能であればほしいです。
ご検討宜しくお願いします。

**Comment by Chipppppppppp** [comment]
https://github.com/Chipppppppppp/LIME/commit/36777e3cd58b1ca553f5c149724110adf64e0ea1
対応しました。

**Comment by Chipppppppppp** [comment]
ごめんなさい、そのコードは https://github.com/Chipppppppppp/LIME/issues/107 を解決したものなのですが、間違えてこちらに送ってしまいました。
まだトーク非表示は実装できていません。

**Comment by areteruhiro** [comment]
（これ、もしかしたら、実現可能な気かもしれません、時間がある際に試してみます。）

**Comment by areteruhiro** [comment]
試したことメモ
 naver_line のchat テーブルのis_archivedを1にすると非表示になる。
xposed モジュール上でsqliteを用いて、UPDATEしたが、他のフィールドはUPDATEできたが、is_archivedフィールドはUPDATEして、エラーは出なかったが反映されなかった。

adb shell からのis_archivedへのUPDATEは反映することは出来た。


メゾットフックに関しては、


XposedHelpers.findAndHookMethod("t71.d", lparam.classLoader,
    "f", String.class, boolean.class, new XC_MethodHook() {
        @Override
        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
           
            String paramString = (String) param.args[0];
            
          
            XposedBridge.log( paramString );

           
        }
    });

これで、チャットの非表示を有効にするのはこれで確認できたが、
チャットの非表示→表示の場合は、このメゾットは使われていないのでもう少し確認が必要です。

**Comment by areteruhiro** [comment]
試したことメモ
 naver_line のchat テーブルのis_archivedを1にすると非表示になる。
xposed モジュール上でsqliteを用いて、UPDATEしたが、他のフィールドはUPDATEできたが、is_archivedフィールドはUPDATEして、エラーは出なかったが反映されなかった。

adb shell からのis_archivedへのUPDATEは反映することは出来た。

メゾットフックに関しては、


XposedHelpers.findAndHookMethod("t71.d", lparam.classLoader,
    "f", String.class, boolean.class, new XC_MethodHook() {
        @Override
        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
           
            String paramString = (String) param.args[0];
            
          
            XposedBridge.log( paramString );

           
        }
    });

これで、チャットの非表示を有効にするのはこれで確認できたが、
チャットの非表示→表示の場合は、このメゾットは使われていないのでもう少し確認が必要です。

**Comment by areteruhiro** [comment]
sqliteの実行をresponseの際にしていたのが原因でした、
コマンド自体は実行できたので、実装できそうです。

**Comment by areteruhiro** [comment]
一応できたんですけど、非rootだと、
コマンドの実行が起動時にしかできないんですよね
このやり方だと良くないかもです

**Comment by areteruhiro** [comment]
報告
値を変えるのを表示させる直前にすることで、表示させないようにできました。
細かい訂正はところどころありますが、いちどPRします。
https://github.com/user-attachments/assets/2bee9385-e649-4a54-9f4f-8917ad57c587

**Comment by areteruhiro** [comment]
報告
値を変えるのを表示させる直前にすることで、表示させないようにできました。
細かい訂正はところどころありますが、いちどPRします。

**Comment by areteruhiro** [comment]
#221
