### ISSUE TITLE
一時的に通常メッセージとして送信

### ISSUE THREAD

**Issue by shibadogcap** [Chipppppppppp/LIME#121]
### 提案内容

LIMEで「常にミュートメッセージとして送信」をオンにしていると、送信ボタン長押し時に「通常メッセージ」を選んでメッセージを送ってもも相手に通知が届かないようです。
送信ボタン長押しから通常メッセージを選ぶことができると、普段はミュートメッセージ、一時的に通常メッセージという運用ができ、便利になるかと思います。

**Comment by areteruhiro** [comment]
''''
            hookTarget = lparam.classLoader.loadClass("cl5.b");
            XposedBridge.hookAllMethods(hookTarget, "H", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    if (keepUnread)  param.args[0] = Enum.valueOf((Class<Enum>) param.args[0].getClass(), "TO_BE_SENT_SILENTLY");
                }
            });
                
''''
KeepUnreadのスイッチを応用することで一時的にサイレントメッセージで送信できますね

**Comment by Chipppppppppp** [comment]
[0ba6268dbdb1fca44abafec43868445a63ddb454](https://github.com/Chipppppppppp/LIME/commit/0ba6268dbdb1fca44abafec43868445a63ddb454) で、「常にミュートメッセージとして送信」状態でも「通常メッセージ」を選べば通知が届くようになりました。
(通常メッセージとミュートメッセージのボタンを入れ替えたうえで、通常かミュートかを反転させる実装にしました。)
