### ISSUE TITLE
 今後のLimeでトーク履歴のバックアップを利用出来るようにはなりますか？

### ISSUE THREAD

**Issue by SDCARD-broken** [Chipppppppppp/LIME#126]
### 提案内容

現在のLime(非root環境)にてトーク履歴のバックアップを作成しようとすると、
![Screenshot_20240511_201432_LINE](https://github.com/Chipppppppppp/LIME/assets/169517657/d45593bd-0ecc-4f44-ae1e-91dce52bb4c7)画像のように表示され、バックアップがとれません。
バックアップをとる裏技的な方法や、今後の開発によってバックアップに対応するご予定はありますでしょうか？

**Comment by s1204IT** [comment]
#50 
こちらで検討されています。  
しかし、この問題はそう簡単に修正できるものではないので、時間を要します。
