### ISSUE TITLE
（注意喚起）以前作動していた、PCとしてログインを行うとそのアカウントからメッセージを相手に送信出来なくなります。

### ISSUE THREAD

**Issue by areteruhiro** [Chipppppppppp/LIME#129]
### LSPatch 使用の有無

- [ ] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

手順通りに

### 再現する手順

手順通りに

### 有効にしている LIME の設定

PC (DESKTOPWIN) に偽装

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by areteruhiro** [comment]
現在なっていて、まだ治らないです。
PC本体からのログインや、拡張機能からのログインも一時的に制限されています。というエラーが発生しています。

**Comment by areteruhiro** [comment]
![image](https://github.com/Chipppppppppp/LIME/assets/108941410/a63993e4-be09-411a-92c6-1906567da7e1)

**Comment by areteruhiro** [comment]
多分、一時的にアカウント停止を食らっていますね。

![Screenshot_2024-05-26-00-57-28-349_jp.naver.line.android.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/9838cc80-7333-450c-80b9-90624e8f6b62)

![Screenshot_2024-05-26-00-57-36-705_jp.naver.line.android.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/434c865f-eda6-4107-8838-bed8fc98ed5d)

経過報告はまたしますね。

**Comment by areteruhiro** [comment]
案の定招待もできないですね。

**Comment by areteruhiro** [comment]
botへの送信は可

**Comment by areteruhiro** [comment]
今治りましたね。

**Comment by areteruhiro** [comment]
おそらく30分間のBANで、その間のメッセージは解除後も相手に送信されません

**Comment by Chipppppppppp** [comment]
完全に LIME が監視されている可能性が出てきましたね。すくなくとも複数デバイスログインボタンが消えたところから、対策したことは確かです。

**Comment by areteruhiro** [comment]
閉じます
