### ISSUE TITLE
自分のスマホで設定するとアプリが開かない

### ISSUE THREAD

**Issue by HMYMizuyoukan** [Chipppppppppp/LIME#135]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

Redmi Note 13 Pro 5G(XIG05)(※root化してない)にREADME通りの手順・バージョンでインストール。
LINEの初期設定も終わらせLIMEの設定の
「既読を付けない」「常にミュートメッセージ」「送信取り消しを拒否」
を設定し、自動的に「再起動しています」というダイアログが表示されたが、アプリが終了された。
だから、ホーム画面から手動でLINEを開いたら、一秒ほどタイトル画面(緑で大きくLINEの文字)が表示された後すぐに閉じてしまい、開けなくなった。

### 再現する手順

XIG05にREADME通りインストールし、LIMEの設定を行う
※すみません。「有効にしているLIMEの設定」ですが覚えていません。但し、初期状態でONになっていたものは全く変えておらず、そこに「常に既読を付けない」「常にミュートメッセージとして送信」「送信取り消しを拒否」を追加でONにしただけです。
あとLINEの初期設定のところで、「Android IDを偽装」みたいなやつもONにしました。

### 有効にしている LIME の設定

VOOM アイコンを削除, ウォレットアイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, WebView を規定のブラウザにリダイレクト, 常に既読をつけない, 送信取り消しを拒否, 常にミュートメッセージとして送信, Android ID を偽装

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by s1204IT** [comment]
「Android ID を偽装」を使用せずに最初からやり直してください。

**Comment by HMYMizuyoukan** [comment]
すみません。
それで解決しました。ありがとうございます。
