### ISSUE TITLE
[Bug]: 広告が削除できない

### ISSUE THREAD

**Issue by akir45** [Chipppppppppp/LIME#140]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

ホームで広告が消えず、下にスクロールするとホームの全ての項目が消えてしまいます。

LINE v14.8.0
LIME v 1.9.0

### 再現する手順

広告を削除 を有効
↓
ホームを開く

### 有効にしている LIME の設定

VOOM アイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, ブラウザアプリで開く, 送信取り消しを拒否, トラッキング通信をブロック (ベータ), LINE バージョンの確認を停止

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by s1204IT** [comment]
アプリを強制停止した後、キャッシュを削除してから、もう一度[リリースから**1.9.0**の**LIME**](https://github.com/Chipppppppppp/LIME/releases/tag/v1.9.0)と[APKMirrorから**14.8.0**の**LINE**](https://www.apkmirror.com/apk/line-corporation/line/line-14-8-0-release/line-calls-messages-14-8-0-android-apk-download/)をダウンロードし、LSPatch をやり直してから、再度試みて下さい。

**Comment by akir45** [comment]
再度インストールし再パッチして、キャッシュを削除したりしましたが、この問題は直りませんでした。

**Comment by areteruhiro** [comment]
自分も不具合確認しました、アプリ側で少し仕様が変更されているようです。

**Comment by Chipppppppppp** [comment]
v1.9.1 で直っていると思います。

**Comment by akir45** [comment]
直りました。ありがとうごさいます
