### ISSUE TITLE
「未読のまま閲覧」スイッチがない

### ISSUE THREAD

**Issue by harutoku** [Chipppppppppp/LIME#142]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

Android14、galaxy s23、nonroot環境において、「未読のまま閲覧」スイッチが存在しない。
「未読のまま閲覧」スイッチを削除の設定をオンオフしても変わらない。
強制停止後再起動したが効果がない。

### 再現する手順

LINE  14.8.0にLIME 1.9.0を適用してパッチした。

### 有効にしている LIME の設定

VOOM アイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, LYP プレミアムのおすすめを削除, 通知から "通知オフ" アクションを削除, WebView を規定のブラウザにリダイレクト, トラッキング通信をブロック (ベータ)

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by harutoku** [comment]
![Screenshot_20240609_165346_LINE](https://github.com/Chipppppppppp/LIME/assets/123850345/fb38b77a-e829-411a-9951-61beb9a507ef)

**Comment by areteruhiro** [comment]
root 環境だと表示されますね。
![Screenshot_2024-06-09-21-51-54-570-edit_jp.naver.line.android.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/68895317-067c-404d-803e-7fafc8ab9af3)

**Comment by harutoku** [comment]
追記、常に未読のまま閲覧をオンにしても機能せず、既読がつきました。
別のissueのほうが望ましいですかね

**Comment by harutoku** [comment]
追追記です
LIME v1.10.0におきましては、JingMatrix氏のlspatchでLINE14.16.0にパッチしたところ、変わらずボタンは表示されませんでした。

**Comment by areteruhiro** [comment]
これ、SharedPerenceを利用しているので
その影響な気がします。
ファイルに直接設定状態を書き込むようにすると、表示されるようになるかもしれません。

**Comment by areteruhiro** [comment]
多分これ直せたとおもいます。動作確認してからPRしますね

**Comment by areteruhiro** [comment]
![Screenshot_20241009-005630.png](https://github.com/user-attachments/assets/9eeb3c01-48d4-4781-9e2d-9c17074174bc)

動作確認しました。
