### ISSUE TITLE
[Feature Request]: 既読時刻の可視化

### ISSUE THREAD

**Issue by korokke2** [Chipppppppppp/LIME#153]
### 提案内容

個人チャットで相手がいつ既読を付けたかを確認できるようにする。
また、グループチャットでも、いつ誰が既読を付けたかを確認できるようにする。

以上よろしくお願いします。

**Comment by s1204IT** [comment]
一つの Issue に複数のリクエストをしないでください。
誰が既読を付けたか確認出来る機能は #54 で検討されています。

また、「相手がいつ」既読を付けたかどうかは、受信者側の時刻で判断されるため、正確な時間は取得出来ない可能性があります。  
端末がオフラインの場合は再接続された時の時刻になります。

**Comment by Chipppppppppp** [comment]
こちら申し訳ないですが、LINE の仕様的に不可能なので閉じさせていただきます。
