### ISSUE TITLE
[Feature Request]: Wear OS版LINEのログインに関して

### ISSUE THREAD

**Issue by Fuku856** [Chipppppppppp/LIME#156]
### 提案内容

Wear OSのLINEでは、スマホのバージョンが最新でなければログインすることができません。
スマホのLINEバージョンの偽装などの機能の実装で解決できるかもしれません。
よろしくお願いします。
- Galaxy Watch6

![Screenshot_20240828_085710_android](https://github.com/user-attachments/assets/8c72061c-5696-4ab1-b259-2bc80d685b22)
![Screenshot_20240828_085714_android](https://github.com/user-attachments/assets/a6e6c8ca-eaed-483f-9be5-4e69c6a38aa9)

**Comment by areteruhiro** [comment]
これを有効にしてログインしても
![Screenshot_20240829-121239.png をアップロード中…]()

できないですか?

**Comment by Fuku856** [comment]
最大バージョンに偽装をオンにしてログインしようとすると、画像のようなエラーが出ます。
![Screenshot_20240829-122131~2](https://github.com/user-attachments/assets/3eb287ed-4d59-4ece-bfe7-97806d7b5a03)

また、バージョン確認を停止しても、wear OS側では、最新バージョンのインストールを促す表示が出てしまいます。
ログの出力はありませんでした。

**Comment by areteruhiro** [comment]
Wear Osを交えたFutureリスエストより、最大バージョンに偽装　が出来ないというbugとして報告してもいいかもしれませんね。

**Comment by areteruhiro** [comment]
Wear osのlineアプリのバージョンは1.3.3ですか？

**Comment by Fuku856** [comment]
1.3.3です
スマホ側はLSPatchです。

**Comment by areteruhiro** [comment]
![image](https://github.com/user-attachments/assets/c3a08d1a-db48-49fe-97df-4a271abb069a)
画像の青のラインをみてもらうと
2024-08-31 22:19:58.260 24053-24073 Finsky                  pid-24053                            I  [58] akon.A(311): jp.naver.line.android is installed but certificate mismatch
とかかれています。
意味はアプリの署名証明が異なるという意味です。
バージョンではなくこちらが原因かもしれません。

また、Lsposed (root)環境ではlineのバージョンを下げてもアップデートしてくださいというエラーはでませんでした。

PCをお持ちなら、wear バージョンのLINEを同じ証明でLSpatchをかけて連携してみると通るかもしれません

**Comment by areteruhiro** [comment]
解決方法みつけました。
以下の1.2.2のLINE WEARをスマートウォッチにapkインストールすることができると、QRコード認証になるので、エラーが発生しませんでした。
https://www.apkmirror.com/apk/line-corporation/line-calls-messages-wear-os/line-calls-messages-wear-os-1-2-2-wear-release/line-calls-messages-wear-os-1-2-2-wear-4-android-apk-download/

**Comment by areteruhiro** [comment]
解決方法みつけました。
以下の1.2.2のLINE WEARをスマートウォッチにapkインストールすることができると、QRコード認証になるので、エラーが発生しませんでした。
https://www.apkmirror.com/apk/line-corporation/line-calls-messages-wear-os/line-calls-messages-wear-os-1-2-2-wear-release/line-calls-messages-wear-os-1-2-2-wear-4-android-apk-download/

QRコード認証を


Galaxy Watch6を持っていないので以下が参考になればと思います、がいつかはこの機能(QRコード認証)も無効化されるかと思います。
https://www.youtube.com/watch?v=Oab9GabAuxc
