### ISSUE TITLE
[Bug] 投票やスタンプショップのリダイレクトを防ぐ

### ISSUE THREAD

**Issue by AioiLight** [Chipppppppppp/LIME#16]
### 内容の詳細

Web View すべてをリダイレクトしているため、投票やスタンプショップ、連絡先といったリンクもリダイレクトされてしまう。
Web View内でしか動かない機能 (投票など) もあるため、リダイレクトする必要のないURLはリダイレクトしない、という挙動が好ましいといえます。

## 改善方法
Xposed APIのログ出力でリダイレクトされると困るURLを見つけ出し、正規表現などでURLをリダイレクトするべきかどうかチェックするようにする。

### 再現する手順

1. 投票などのリンクを開く。
2. 再現。

### モジュールのバージョン

1.1

### LINEアプリのバージョン

14.0.2

**Comment by AioiLight** [comment]
line.me 以外のアドレス

LINE Pay 送金依頼:
pay-webapp.line-apps.com

Yahoo!カレンダー:
line-calendar.yahoo.co.jp

**Comment by Chipppppppppp** [comment]
https://github.com/Chipppppppppp/LIME/commit/e06f2dc4181f40f8b747fafe4ac266ca4198fba5
このコミットによりおおむねバグは解消されたと思います (投票しか試していませんので、他も試す必要がありますが)

**Comment by AioiLight** [comment]
@Chipppppppppp 
見た感じはよさそうです

`SettingsActivity` に `android.intent.category.LAUNCHER` がないからか、ドロワーにアプリがないようです。仕様ですか？

**Comment by Chipppppppppp** [comment]
それバグですね、修正します (いつからか消えてましたね)

**Comment by s1204IT** [comment]
> それバグですね、修正します (いつからか消えてましたね)

ごめんなさい、僕が色々勘違いして消しちゃってました🙇🏻‍♂️

https://github.com/Chipppppppppp/LIME/commit/5d68831
