### ISSUE TITLE
ホームのおすすめが削除されない。

### ISSUE THREAD

**Issue by areteruhiro** [Chipppppppppp/LIME#180]
### LSPatch 使用の有無

- [ ] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

![Screenshot_2024-10-07-07-59-20-563_jp.naver.line.android-edit.jpg](https://github.com/user-attachments/assets/2d59b841-8ea7-4c80-abfe-353fe06d1715)

### 再現する手順

広告を削除 を有効にする

### 有効にしている LIME の設定

広告を削除

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by areteruhiro** [comment]
一応ここまで、削除されてるのは確認しています。

![Screenshot_2024-10-07-08-03-26-312_jp.naver.line.android-edit.jpg](https://github.com/user-attachments/assets/cf743ffa-5bb4-46a5-9db0-2039e0ece293)

**Comment by s1204IT** [comment]
フック先のクラスが間違ってる感じなのですかね？

**Comment by areteruhiro** [comment]
今送ってるプルリクで治るかと思いますが、フック名の方も確認します。

**Comment by s1204IT** [comment]
これで直る様でしたら、#177 も含めて次のパッチリリースを行います。

**Comment by areteruhiro** [comment]
このPRhttps://github.com/Chipppppppppp/LIME/pull/179
と、同様の修正を行ったら、
自分の環境下では修正されました。


一応、リリースする前に、試していただくことはできますか？



あと余談ですが、リリースする際、
コントリビューターとしての私の名前は書いて頂かなくて大丈夫です。

@Chipppppppppp さんがいてこそですから。 

私は便乗しただけですし

**Comment by s1204IT** [comment]
承知しました。
別の人と確認します。

---

Chip さんの次に貢献頂いていますし、実際に今回のリリースを手伝って頂いたので載せたのですが、もし嫌な様であれば記載を削除します。

**Comment by areteruhiro** [comment]
そこまでいっていただけるのならどちらでも大丈夫です〜
