### ISSUE TITLE
[Feature Request]: LIMEのアイコンを作ってみた。

### ISSUE THREAD

**Issue by reindex-ot** [Chipppppppppp/LIME#187]
### 提案内容

アイコンが寂しいのでとりあえず作ってみた。
没にするかは任せます。
![LIME](https://github.com/user-attachments/assets/201f60dc-a6b5-4a3b-81f6-a40364c8f57a)
[LIME_Icon.zip](https://github.com/user-attachments/files/17310617/LIME_Icon.zip)

**Comment by areteruhiro** [comment]
採用されるかはわかりませんし、
私がコメントしていいかは定かではありませんが、
きっとプルリクエストのほうがいいです。

~~（アイコン当初はLIMEという文字があったのですが、今は真緑になっていますね）~~

**Comment by reindex-ot** [comment]
一応プルリクエストの送信をしました。

**Comment by s1204IT** [comment]
一応、Chipさんに連絡しときました(返答待ち)。
ただ、現時点で SVG の修正が無いので、そこのご確認もお願いします。
<https://github.com/Chipppppppppp/LIME/blob/master/app/src/main/res/drawable/ic_launcher_foreground.xml#L2-L29>

**Comment by reindex-ot** [comment]
アイコンがアダプティブ仕様になっていないミスあったんで修正しました。
Adaptive Icon Testerにてレイアウトを確認済みです。

**Comment by s1204IT** [comment]
@reindex-ot 
こちらでも採用しても良いとの事ですので、ぜひPRをお送りください！
SVGはPR時に同時に削除するので、WebP及びPNGのみで構いません
