### ISSUE TITLE
[Feature Request]: 非root環境におけるMicroGのサポート

### ISSUE THREAD

**Issue by misakazip** [Chipppppppppp/LIME#197]
### 提案内容

Google系のサービス（トーク履歴のバックアップ、復元など）が非root環境でも可能な様にMicroGなどによるログインに対応してほしいです。

**Comment by areteruhiro** [comment]
MicroGの対応は、LsPosedでは、対応できないのでRevancedでの対応になります。

トークでのバックアップ、リストアなどは、代替手段として
https://github.com/Chipppppppppp/LIME/pull/195
で、機能追加をしています。

https://github.com/LIME-beta-hiro/
で、先行リリースしています

**Comment by misakazip** [comment]
承知しました！
返信ありがとうございます！
