### ISSUE TITLE
[Feature Request] ｢ホーム｣タブで表示するコンテンツを減らす

### ISSUE THREAD

**Issue by s1204IT** [Chipppppppppp/LIME#24]
### 提案内容

ホームタブにおいて、

- サービス
- おすすめの公式アカウント
- おすすめのスタンプ
- あなたにおすすめの曲
- (LYPの広告)

これらの**各項目を**非表示に出来る様にして欲しいです。

**Comment by Chipppppppppp** [comment]
前々からチャレンジしていますが、なかなかうまくいっていないので成功するまでお待ちください。

**Comment by auag0** [comment]
一旦は RecyclerView(R.id.home_tab_recycler_view)の子ViewのR.id.home_tab_contents_recommendation_placementというリソースIDが付いたLinearLayoutを全て非表示にすれば おすすめの〇〇〇 は除外できそうですが、RecyclerViewなので addOnScrollListenerを使ってスクロールの度に非表示にする必要があるかもです、、？

**Comment by Chipppppppppp** [comment]
そうですね
難読化されたクラスはバージョンごとに名前が変化してしまうため扱わない予定なので、addOnScrollListener をつかうしかないという気がしています

**Comment by Chipppppppppp** [comment]
home_tab_recycler_view や home_tab_contents_recommendation_placement は、Activity から findViewById しようとすると null になってしまい取得できなくて困っていたのですが、どうやりましたか？

**Comment by auag0** [comment]
自分まだ試せてないのですが、ActivityではなくFragmentで表示しているので 以下のHomeFragmentクラスのonViewCreatedで渡されるViewにfindViewByIdで取得できるはずです！
jp.naver.line.android.activity.homev2.view.HomeFragment

**Comment by Chipppppppppp** [comment]
なるほど、ありがとうございます！

**Comment by Chipppppppppp** [comment]
LinearLayout のコンストラクタ呼び出し時に home_tab_contents_recommendation_placement と id が一致するもののみ消すという荒業でとりあえずはできました。(下にスクロールすると謎の広告が残りますが...)
もっといいアプローチがあると思います

**Comment by auag0** [comment]
RecyclerViewのクラスも難読化されてて addItemDecorationやaddOnScrollListener、getViewTreeObserver関数が難読化されていたので、自分の考えていた方法 https://github.com/Chipppppppppp/LIME/issues/24#issuecomment-1903330125 では無理そうでした；；

**Comment by auag0** [comment]
getViewTreeObserverは使えたので おすすめと広告を削除することは出来ましたが、この方法でも空白が出来てしまいます
https://github.com/auag0/LIME/commit/e0b3799deab284a28a97588685828af739175c5c

**Comment by Chipppppppppp** [comment]
いいですね、これ採用したいので、プルリクとして出してくださいますか？

**Comment by auag0** [comment]
すみません、今外出中なので、以下の部分をコピペしていただいて大丈夫です
https://github.com/auag0/LIME/blob/e0b3799deab284a28a97588685828af739175c5c/app/src/main/java/io/github/chipppppppppp/lime/Main.java#L121-L153

**Comment by Chipppppppppp** [comment]
わかりました、ありがとうございます！

**Comment by Chipppppppppp** [comment]
deleteAds のところで、parent まで含めて消すようにしたら、ホームタブの一番下にあった広告は消えました。
おすすめの削除に関しては、addOnScrollListener を使った方法ではなく LinearLayout を使った方法にしましたが、どっちがいいかは少し迷ってます (どっちが軽い・安定しているのか...)

**Comment by auag0** [comment]
LinearLayoutを使った方法でも全然いいと思います！
でも LinearLayoutの初期化時にgetResources().getIdentifier関数を毎回呼び出すとパフォーマンスが低下する可能性があるので、リソースidをキャッシュするようにすればより良くなると思います！(getIdentifierで元々キャッシュされる仕組みなら別ですが)

**Comment by Chipppppppppp** [comment]
結局 addOnScrollListener の実装にしてちょっと工夫を加えることで空白を消すようにしました
