### ISSUE TITLE
[Feature Request] レイアウトのカスタマイズ

### ISSUE THREAD

**Issue by reindex-ot** [Chipppppppppp/LIME#25]
### 提案内容
![20240121_104608](https://github.com/Chipppppppppp/LIME/assets/32851879/3aa93140-93db-46ad-b4d9-3fa589e1aa0b)

UIのカスタマイズがメインです。
海外ユーザー向けのカスタマイズ項目もあります。

- サービスのアイコンサイズの変更(海外UI向け)
- サービスのアイコンラベルの削除
- Keepとオープンチャットなどにダークテーマを適用
- ボトムメニューのラベルを削除

**Comment by Chipppppppppp** [comment]
ボトムメニューのラベル削除のみ追加しました。
Keep は自分の場合普通にブラック着せ替えが効いているのですが、そちらではどうなっているのでしょうか...？
また、サービスに関しては少し面倒なのでおいおい進めていきます。

**Comment by reindex-ot** [comment]
Keepはダークモードではブラック着せかえ適用でダーク化できました。

**Comment by Chipppppppppp** [comment]
オープンチャットなど、というのは「サービス」から移動できるもののことでしょうか？
それでしたら WebView で実装されているので、WebView のカスタマイズをすれば行けそうです。
