### ISSUE TITLE
Materialアイコン、予測型バックジェスチャー、未読で閲覧、マーキング機能のサポート

### ISSUE THREAD

**Issue by ghost** [Chipppppppppp/LIME#35]
### 提案内容

![Screenshot_20240124-091634](https://github.com/Chipppppppppp/LIME/assets/157547047/41ce3583-18a1-453f-967b-ae03e93066d1)
上記のようなマテリアルアイコンと予測型戻るアニメーションのサポートをしていただきたいです
また、未読で閲覧する機能やTelegramやGoogleメッセージにあるような未読マークを付ける機能を実装していただきたいです

**Comment by Chipppppppppp** [comment]
Material アイコンの実装はおそらく LSPosed では困難なことと、未読で閲覧する機能は実装されたことを理由にいったん閉じておきます。(未読マークを付ける実装は立て直されたら考えます)
