### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLEエラー

### ISSUE THREAD

**Issue by yuubinnkyoku** [Chipppppppppp/LIME#42]
### 内容の詳細

INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package jp.naver.line.android signatures do not match newer version; ignoring!というエラーが発生する

### 再現する手順

非root端末でLS Patchを利用してパッチしたが、インストール時にこのエラーが発生し、インストールできない
「インストールされているアプリを選択」からも「ストレージからapkを選択」も、LINE側、モジュール側それぞれ試したが同様のエラーが発生する

### モジュールのバージョン

1.2

### LINEアプリのバージョン

14.0.1

**Comment by Kdroidwin** [comment]
LINE(パッチをあてていない)をアンインストールしましたでしょうか?

**Comment by yuubinnkyoku** [comment]
> LINE(パッチをあてていない)をアンインストールしましたでしょうか?

アンインストールしたのですが、仕事用アプリのLINEを消すのを忘れていました…
消したら上手く行きました！ありがとうございます
