### ISSUE TITLE
[Bug] LSPatch を使用した場合設定の変更ができない

### ISSUE THREAD

**Issue by Chipppppppppp** [Chipppppppppp/LIME#45]
### 内容の詳細

LSPatch を使用した場合設定のボタンが表示されません。

おそらく SharedPreferences をアプリの起動時に読み込む方法から XSharedPreferences で読み込む方法に変えた (#43) ことで発生しています。

### 再現する手順

LSPatch でパッチを適用した apk をインストールし、設定を開く

### モジュールのバージョン

1.3

### LINEアプリのバージョン

14.0.2

**Comment by Chipppppppppp** [comment]
完全な勘違いでした！すみません！
なぜかもう一回やったらいけました！

**Comment by s0racat** [comment]
LIME本体をインストールしないとLSPatch版は設定できないようです
