### ISSUE TITLE
ダイアログがはみ出る可能性がある

### ISSUE THREAD

**Issue by AioiLight** [Chipppppppppp/LIME#48]
### 内容の詳細

ピクセル密度が低いデバイスや、文字が極端に大きいデバイスなどでLIMEのダイアログを開くと設定項目がはみ出て操作できなくなる可能性があります。
また将来的に設定項目が増えた際にも問題なく動作するよう、ダイアログ内がスクロールできるようになると望ましいです。（どちらかというとこちらの意味合いが強いです）

![Screenshot_20240129-143131_LINE](https://github.com/Chipppppppppp/LIME/assets/13918537/b1fb98f9-4f9a-400d-b9f9-c9eb384617a5)

### 再現する手順

- 画面の小さい端末や、表示サイズを極端に大きくした端末を用意する
- 再現

### モジュールのバージョン

1.3

### LINEアプリのバージョン

14.0.2

**Comment by Chipppppppppp** [comment]
[b2d7726 ](https://github.com/Chipppppppppp/LIME/commit/b2d7726166ab06c5befaf46dd0c435ac8a40e898) で解決しました。
