### ISSUE TITLE
[Feature Request] ボトムバーの各ラベルの当たり判定の拡張

### ISSUE THREAD

**Issue by salmon-21** [Chipppppppppp/LIME#52]
## 問題
ラベルの当たり判定が青色の部分にしか存在せず、ピンク色の位置でタップしてもタブを切り替えることができません。
VOOMアイコンとウォレットアイコンを削除するとこの問題が顕著になります。

## 改善
当たり判定を青色の部分まで拡張すると使い勝手がかなり向上するかもしれません。

![image](https://github.com/Chipppppppppp/LIME/assets/52450144/4caac72d-98b0-4409-80d3-55ce3fe1e405)

**Comment by Chipppppppppp** [comment]
https://github.com/Chipppppppppp/LIME/commit/270d3c038ca3ae6dc70a78858c6cbdeb6e20d5fa
対応しました。
