### ISSUE TITLE
既読つけないスイッチのダークモード対応

### ISSUE THREAD

**Issue by yuubinnkyoku** [Chipppppppppp/LIME#53]
### 提案内容

![Screenshot_20240204-111534](https://github.com/Chipppppppppp/LIME/assets/137483288/80c2d6bd-bc8a-457f-bd74-3ca503a63df9)
ダークテーマ適用中だと目立つので…

**Comment by Chipppppppppp** [comment]
(スイッチをオフにした状態で LINE を再起動すると意図せず既読をつけてしまうため) そのスイッチは次のバージョンで削除予定です。

LINE 起動時の既読をつける挙動をオフにするわけにもいかないので、よりいい方法を思いついて再起動時も未読のままで済むようになったら復活するかもしれません。
