### ISSUE TITLE
2次配布や改変などについて

### ISSUE THREAD

**Issue by hiroki1114** [Chipppppppppp/LIME#56]
### 提案内容

@Chipppppppppp さんのこのモジュールがきっかけでxposed moduleの作成に興味が持ちました。

lineのバージョンアップなどの際、クラスやメソッド名が変わってしまうと思うのですが、その際は個人利用なら、改変させていただいても大丈夫でしょうか。(既読キャンセルに関して)

**Comment by s1204IT** [comment]
その際は、リポジトリをフォークして修正を行い、プルリクエストを出してもらうのが一番良いと思われます。

**Comment by hiroki1114** [comment]
ご丁寧にご返信ありがとうございます

**Comment by s1204IT** [comment]
今見てみましたが、出されていませんね。

<https://github.com/Chipppppppppp/LIME/compare/master...hiroki1114:LIME:master>
このページの <btn><b>Create pull request</b></btn> を押してタイトルを入力して同じボタンを押せばプルリクエストが出せます。

---

余談ですが、README での修正部分のスタイルが崩壊しているので、修正した方が良いと思います。

```patch
diff --git a/README.md b/README.md
index 0051071..efb51dd 100644
--- a/README.md
+++ b/README.md
@@ -7,7 +7,7 @@

 This is an Xposed Module to clean [**LINE**](https://line.me). It suppports **LINE 14.0.2**.

-LINE を掃除する Xposed Module です。--**LINE 14.0.2** に対応しています。-- 14.1.2
+LINE を掃除する Xposed Module です。14.1.2
```

**Comment by hiroki1114** [comment]
もう一度ためします🙇
ありがとうございます

**Comment by hiroki1114** [comment]
多分できました
com.linecorp.line.ladsdk.ui.inventory.openchat.LadOpenChatHeaderAdView　クラスも　が消えていたので消しています

**Comment by Chipppppppppp** [comment]
諸事情で日本版 LINE にログインできなくなってしまったので、新バージョンで広告ブロック系は試せていないんですよね... (海外版は広告がない)
日本版 LINE は電話番号が必要なので電話番号を新しく取得しようかと思っているので、ちょっと時間かかるかもしれません (抜け道があればいいのですが...)

**Comment by akir45** [comment]
上記の国でインドネシアのみ電話番号なしで登録でき、広告は出ませんがオススメは表示されました

**Comment by hiroki1114** [comment]
自分、日本版なのですが
広告系は本体設定のdnsに
``dns.adguard-dns.com``登録してて、あんまり紀にしないんですよね

**Comment by hiroki1114** [comment]
read のクラス　`nl5.jp`です、さっきまで間違ってましたすみません
