### ISSUE TITLE
[Bug?]すべて既読にするの動作

### ISSUE THREAD

**Issue by shibadogcap** [Chipppppppppp/LIME#57]
### 内容の詳細

「既読をつけない」がオンだとトーク画面右上のメニューの「すべて既読にする」及び、トーク相手やグループ名を長押しした際の「既読にする」が機能しません。
「既読をつけない」機能では意図的に既読をつけようとする動作も防ぐのが正常な動作でしょうか？

### 再現する手順

既読の有無に関わらずまだ見ていないメッセージがある場合（トーク相手やグループの名前の右側に数字が表示されている状態のとき）、トーク画面の右上のメニューから「すべて既読にする」を押すことができるものの、トーク相手から既読表示が確認できない。あるいはトーク相手やグループ名を長押しした際のメニューにも同様のボタンがあるが、押しても相手から既読表示が見られない。

### モジュールのバージョン

1.4

### LINEアプリのバージョン

14.0.2

**Comment by Chipppppppppp** [comment]
現状、既読をつけないのは既読の通信をすべてブロックすることによって達成しているためこの動作は仕様です。

ただ、この方法だといろいろと問題があるため、よりいい手段が見つかれば改善する予定です。

**Comment by Chipppppppppp** [comment]
v1.6.0 で追加された「未読のまま閲覧」スイッチなら「すべて既読にする」も使えると思います。
