### ISSUE TITLE
[Bug] 設定、呼び出し

### ISSUE THREAD

**Issue by ayumunoheya** [Chipppppppppp/LIME#58]
### 内容の詳細

galaxy s23 one ui 6 root無し
lspatch v0.6

•何度再インストールしても設定ボタンが表示されない。
•通話の呼び出し音がならない
•line通話の通知を使用をオンにした際のバイブレーションがならない

上記のバグが発生しております。呼び出し音はデフォルトのままで、設定のプレビューも鳴りません。おま環でしたら申し訳ございません。何卒よろしくお願いいたします。

### 再現する手順

インストール後、ログイン

### モジュールのバージョン

1.4

### LINEアプリのバージョン

14.0.2

**Comment by hiroki1114** [comment]
横から失礼します、LSPatchのバージョンもよろしければお願いいたします。

また初期の通話音声がならないということでしょうか？
（カスタムされた着信音でしょうか）

それとも、両方の場合でしょうか。

**Comment by yousandesu** [comment]
> ### 内容の詳細
> galaxy s23 one ui 6 root無し
> 
> •何度再インストールしても設定ボタンが表示されない。 •通話の呼び出し音がならない
> 
> 上記のバグが発生しております。おま環でしたら申し訳ございません。何卒よろしくお願いいたします。
> 
> ### 再現する手順
> インストール後、ログイン
> 
> ### モジュールのバージョン
> 1.4
> 
> ### LINEアプリのバージョン
> 14.0.2

同じくGALAXYs20 one ui 5で着信音、呼び出し音がなりません...
Limeの設定ボタンは自分の環境では出ています。
着信音、呼び出し音は設定のプレビュー再生の時点で音が鳴りません...

**Comment by Chipppppppppp** [comment]
設定ボタンが出ないことに関しては、README.md にもあるように、LSPatch した LINE アプリとは別に LIME アプリをインストールすることでおそらく解決するかと思われます。

着信音・呼び出し音がならないのは、Google アカウントにログインできない問題と同じで GMS が動作しないからではないかと推測しています (これに関しては全く詳しくないので、あとで調べようと思います)

**Comment by yousandesu** [comment]
> 設定ボタンが出ないことに関しては、README.md にもあるように、LSPatch した LINE アプリとは別に LIME アプリをインストールすることでおそらく解決するかと思われます。
> 
> 着信音・呼び出し音がならないのは、Google アカウントにログインできない問題と同じで GMS が動作しないからではないかと推測しています (これに関しては全く詳しくないので、あとで調べようと思います)

ありがとうございます。着信音、呼び出し音はデフォルトの音が設定できないだけで端末の設定で他の音は鳴らせるので自分はYouTubeから同じ音源を拾ってきて、同じように再現はできました🙇‍♂️
今の機能で物凄く感謝しています！開発頑張ってください！
