### ISSUE TITLE
デュアルメッセンジャー利用時にLIMEの設定が反映されない

### ISSUE THREAD

**Issue by 74no** [Chipppppppppp/LIME#59]
デュアルメッセンジャー機能でLINEを1端末に2つ入れています。

サブのLINEでLIMEの設定を変更後、再起動しても設定が反映されず、デフォルトの状態に戻ってしまいます。

メインのLINEではLIMEの設定変更が反映されるので、もとに戻るのはサブアカウントの方だけです。

モジュールのバージョン：1.4
LINEアプリのバージョン：14.0.2
端末：GalaxyA20

解決策があればご教示いただけたら幸いです。

**Comment by 74no** [comment]
モジュールのバージョン：1.4
LINEアプリのバージョン：14.0.2
端末：GalaxyA20

**Comment by Chipppppppppp** [comment]
Pixel 6a 上の PixelXpert を利用したアプリクローンで同様の症状は確認していますが原因究明中です。

**Comment by Chipppppppppp** [comment]
XSharedPreferences がなぜかマルチユーザーだとうまくいっていないっぽいので、設定を LINE に埋め込まずに LIME アプリで設定するようにすればいけそうなことはわかりました。

LINE アプリに埋め込んだ設定と埋め込んでいない設定のどちらも使えるようにすれば問題はないのですが、よりいい方法がないか考えておきます。

**Comment by 74no** [comment]
原因調査ありがとうございます!
気長に待たせていただきますー

**Comment by Chipppppppppp** [comment]
v1.6.0 にて LIME アプリから設定することが可能になったので、LIME アプリから設定することで対応できると思います。

**Comment by 74no** [comment]
ありがとうございます。

v1.6.0のリリースには
＞LSPatch 版で LIME アプリのインストールが不要に
とありますが、[readme](https://github.com/Chipppppppppp/LIME?tab=readme-ov-file#%E9%9D%9E-root-%E7%AB%AF%E6%9C%AB)には
＞2. LIME アプリをインストール
とあります。

一度インストールした後で、アンインストールするということでしょうか?

無知で大変恐縮ですが、手順を教えていただけると幸いです。

**Comment by Chipppppppppp** [comment]
README.md のほうが間違っていたので修正しました

**Comment by Chipppppppppp** [comment]
LIME アプリのインストールは不要なので、アンインストールしてしまって構いません

**Comment by 74no** [comment]
確認しました、ありがとうございます!
トークの復元に苦戦していて、まだメインの端末に移行出来ていませんが、これから重宝しそうです。

ご対応いただきありがとうございました!

**Comment by Chipppppppppp** [comment]
トークバックアップにまだ非 root 版はまだ対応してませんね... 将来対応したいと思っているのでがんばります

**Comment by areteruhiro** [comment]
閉じているのにコメントするのどうかとおもいましたが、
`      XposedBridge.hookAllMethods(Application.class, "onCreate", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Application appContext = (Application) param.thisObject;` 
                で、naver_line全部バックアップすればできそうじゃないですか？
