### ISSUE TITLE
Rootなしで動作しない

### ISSUE THREAD

**Issue by Kdroidwin** [Chipppppppppp/LIME#6]
LsPatch等でパッチを当てるとログインすることはできるもののgw.line.naver.jp へのアクセスが拒否されましたと表記が出ます。
やはりRootなしで動作は不可能でしょうか?

自分はメイン端末は諸事情によりRoot化していないので対応していただけたら非常に嬉しいです。

![Screenshot_20240119-185456](https://github.com/Chipppppppppp/com.example.lime/assets/144515909/70210989-f9c0-4d02-ba11-f5e783e5b8bc)

ちなみにAdGuard等のVPNアプリは使用していません。

**Comment by Kdroidwin** [comment]
タイトルミスです。「Rootなしで動作」のま違いです。

**Comment by Kdroidwin** [comment]
補足ですがログイン後LINEアプリを起動した直後にこうなります。

**Comment by Chipppppppppp** [comment]
自分の環境では v1.2 で LSPatch 動作したのですが、どうでしょうか...？
まだ LINE 内に設定を埋め込んでいない関係上、設定の変更には対応していませんが

**Comment by kitadai31** [comment]
横から失礼します、これはLSPatchの問題ではなくWebViewリダイレクトの問題 (#16) ではないでしょうか？
その画像はWebView内でしか動かない機能がChromeで開かれてしまっている状態のように見えます
もしそうであればv1.2で既に修正されています

なお私の環境ではv1.0の頃からLSPatchで動作しています

**Comment by Kdroidwin** [comment]
報告遅れました。
v1.2でなら動作しました。
ありがとうございました。
