### ISSUE TITLE
[Feature Request] 常にミュートモードでメッセージを送信

### ISSUE THREAD

**Issue by hiroki1114** [Chipppppppppp/LIME#61]
事故防止でnormalメッセージとして送信してしまうのをなくしたい

**Comment by hiroki1114** [comment]
@Chipppppppppp メンション失礼します。

**Comment by hiroki1114** [comment]
メッセージ、画像、スタンプはオートミュート実装できましたが

ファイルとボイスメッセージは、ミュート化自分では出来なかったです。

ちなみに、
Labのサイレントメッセージをオフにしていてもミュート送信されました。

（今、スマホのラインが、14.1.3で止まっているので、時間があるときに、最新版のメゾット探しておきます）

**Comment by Chipppppppppp** [comment]
コードを提供してくれたら採用するかもしれないので、プルリクとして送ってもらえると助かります

**Comment by hiroki1114** [comment]
遅れてすみません、Pullリクエストしました~~自分のスマホが14.2.0までの更新しかストアに来ていなくて、地味に手こずりました~~

**Comment by Chipppppppppp** [comment]
これ謎ですよね、apkmirror には 14.2.0 来てるので取り消したんでしょうか...？ (Google Play の仕様がよくわからない)

**Comment by hiroki1114** [comment]
Micoro-G調べてる感じすごいハードル高そうですね。

Vancedのソースコード？っぽいのあったので
一応貼っておきます。

Vanced Source Code Archive
https://archive.org/details/yt-vanced

YouTube Vanced API
https://archive.org/details/vanced-api
