### ISSUE TITLE
[Bug] Hide Recommendation does not work at all

### ISSUE THREAD

**Issue by TV-Toshikawa** [Chipppppppppp/LIME#63]
### 内容の詳細

I still can see Recommended Songs, Trending videos from boom, and Openchats with disgusing skibidi stuff.

### 再現する手順

No need to explain here, enable hide recommendation and there is issue.

### モジュールのバージョン

1.4

### LINEアプリのバージョン

14.1.3

**Comment by Chipppppppppp** [comment]
LIME v1.4 only supports LINE v14.0.2.
I released LIME v1.5, which is compatible with LINE v14.1.3. Give it a try.
https://github.com/Chipppppppppp/LIME/releases/tag/v1.5
