### ISSUE TITLE
[Bug] 仕事用プロファイル内のLINEにて、LIMEの設定が変更できない。

### ISSUE THREAD

**Issue by M4S4K4R1** [Chipppppppppp/LIME#65]
### 内容の詳細

Android13(Root化済み/ Magisk 27001)、LSPosed環境にて確認。

仕事用プロファイル内のLINEにて、LIMEの設定を変更。
設定反映のためにLINEを再起動すると、LIMEが初期設定の状態に戻ってしまう。

### 再現する手順

[Shelter](https://f-droid.org/ja/packages/net.typeblog.shelter/) を使用し、仕事用プロファイルへLINEを追加。
LSPosedから、LIMEを仕事用プロファイルへ追加し、LIMEのモジュールを有効にし、LINEアプリへチェックを入れる。

LINE→⚙→LIME→{任意の設定項目を変更}→OK→LINE再起動

### モジュールのバージョン

1.5

### LINEアプリのバージョン

14.1.3

**Comment by Chipppppppppp** [comment]
#59 と同じ症状だと思われるので、#59 が解決すればこちらも解決されそうですね

**Comment by Chipppppppppp** [comment]
v1.6.0 にて LIME アプリから設定することが可能になったので、LIME アプリから設定することで対応できると思います。
