### ISSUE TITLE
[Feature Request]: 新しいグループに参加した際に規定でミュートする

### ISSUE THREAD

**Issue by EggToaster** [Chipppppppppp/LIME#68]
### 提案内容

~~My lifeless friends abuse system of line to wake me up while sleeping or doing important stuff.~~
~~i know this app is for ad blocking, but i will help when i can.~~

グループに自動追加された際に規定でトーク通知をミュートにする機能の追加

**Comment by s1204IT** [comment]
~~無駄な言葉が多すぎて結論が分かりにくいのですが、~~

グループに自動追加された際に規定でトーク通知をミュートにする

と言う事がリクエスト内容で合っていますか？

**Comment by TV-Toshikawa** [comment]
はい、そういう事です。

**Comment by s0u7a** [comment]
I have the same request.

**Comment by hiroki1114** [comment]
This is off-topic, but if you use a notification management app, you will no longer receive unnecessary notifications.
（ex [Norg]()https://play.google.com/store/apps/details?id=com.lufesu.app.notification_organizer）

**Comment by TV-Toshikawa** [comment]
Sadly, i dont want entire notifications to be gone. I could just disable notifications but important message wont be shown.

**Comment by hiroki1114** [comment]
You can register important notifications.

**Comment by Chipppppppppp** [comment]
残念ながら、これは嘘でした。

**Comment by Chipppppppppp** [comment]
Unfortunately, it was a mistake. If the correct method which disables notifications could be found, there might be a possibility to implement it.

**Comment by s1204IT** [comment]
以後、日本語で討論をお願いします。

**Comment by areteruhiro** [comment]
notificationDisabled:false
メモ

**Comment by areteruhiro** [comment]
@EggToaster 
規定というのは、
招待されたら自動で通知をオフにするということですか？？
それとも招待してくれた人で判断しますか？

**Comment by EggToaster** [comment]
前半が合っています。勝手にグループに招待されても通知が鳴らないようにしたいです。

**Comment by areteruhiro** [comment]
すみません、少しうまくいかないので
後回しにさせてもらいます。

**Comment by areteruhiro** [comment]
少し、思ったやり方とは違いますが、実装できました。
PRします。
