### ISSUE TITLE
[Bug] 未読のまま閲覧スイッチ

### ISSUE THREAD

**Issue by yousandesu** [Chipppppppppp/LIME#72]
### 内容の詳細

バージョンで新しく追加された、機能ですが未読のまま閲覧スイッチはタスクキルするとスイッチがオフになるのは仕様でしょうか？常時ではなく、読もうとする時にオンにするという感じでしょうか？

また、既読をつけないをオンにした場合、スイッチは機能しないのでしょうか？

### 再現する手順

既読をつけないをオフにする
↓
未読のまま閲覧スイッチをオン
↓
送信して既読がつくのを確認
↓
タスクキル後再度LINEを開く
↓
スイッチがオフになっている

### モジュールのバージョン

1.6

### LINEアプリのバージョン

14.2.0

**Comment by Chipppppppppp** [comment]
スイッチをオンにしていると未読の黄緑色のバッジが消えず不便なので、常にオンにすることは想定していないです。

また、「既読をつけない」がオンの場合も、未読バッジを消さずに閲覧するという用途で使用できます。

**Comment by yousandesu** [comment]
了解しました！バージョンが更新されると、どんな機能が追加されるのかとても楽しみで、更新をこまめにチェックしてます！とても重宝しています！開発頑張ってください！

**Comment by Chipppppppppp** [comment]
ありがとうございます！！
