### ISSUE TITLE
[offer] line hack xposed のapk(line 9.2.2まで)

### ISSUE THREAD

**Issue by hiroki1114** [Chipppppppppp/LIME#76]
### 提案内容

ご存知かとは思いますが、昔あったline hack xposedモジュールのapkです

[com.cdgod.linehack-6b7d96fadde2e54c0711d7a57d3abf07.zip](https://github.com/Chipppppppppp/LIME/files/14328246/com.cdgod.linehack-6b7d96fadde2e54c0711d7a57d3abf07.zip)
同じファイルがもうネットから消されているようなのでアーカイブ用に投稿させていただきました。

**Comment by hiroki1114** [comment]
![Screenshot_2024-02-19-17-07-19-055_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/547a35b4-db2c-4677-958e-18125b253df4)

![Screenshot_2024-02-19-17-15-35-046_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/a7279233-f9f9-45c7-8693-ba36e291674b)

![Screenshot_2024-02-19-17-15-39-346_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/38a7a4aa-5fd3-4e1a-8162-74b36ed94c56)

![Screenshot_2024-02-19-17-15-42-097_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/40820ee1-622c-4a57-9eb9-01584abde5d7)

![Screenshot_2024-02-19-17-15-46-206_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/507175fa-dd9f-4557-821d-29672eac1a07)

**Comment by hiroki1114** [comment]
![Screenshot_2024-02-19-17-15-35-046_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/9cb8a19d-9429-4859-a6eb-249c850fa375)

![Screenshot_2024-02-19-17-15-39-346_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/6efed3dd-7064-420b-8712-a5e1fabfcaf9)

![Screenshot_2024-02-19-17-15-42-097_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/7d195bff-1eb9-4751-a663-e6ae79611bf3)

![Screenshot_2024-02-19-17-15-46-206_com.cdgod.linehack.jpg](https://github.com/Chipppppppppp/LIME/assets/108941410/b778d48a-410d-43b1-974f-930082ccb926)

**Comment by Chipppppppppp** [comment]
ありがとうございます～
