### ISSUE TITLE
広告を削除有効時にニュースが正しく表示されない

### ISSUE THREAD

**Issue by areteruhiro** [Chipppppppppp/LIME#77]
### 内容の詳細

ある意味仕様だと思うので、修正は個人的には、どちらでも大丈夫です。報告だけしておきます。

有効時
![Screenshot_2024-02-22-10-51-22-423_jp naver line android](https://github.com/Chipppppppppp/LIME/assets/108941410/c3924f5d-a16d-4dbc-bb25-2e97f3dda6c7)

無効時
![Screenshot_2024-02-22-10-51-54-793_jp naver line android](https://github.com/Chipppppppppp/LIME/assets/108941410/10e6db94-334c-42eb-8c1a-68a4ae4384e4)

### 再現する手順

 有効にして、ニュース公式LINEを開く。

### モジュールのバージョン

1.6

### LINEアプリのバージョン

14.2

**Comment by Chipppppppppp** [comment]
v1.7.0 をリリースしたので、これで修正されたかと思います。

**Comment by areteruhiro** [comment]
感謝します。
