### ISSUE TITLE
[Feature Request] 取り消されたメッセージを分かるようにする

### ISSUE THREAD

**Issue by areteruhiro** [Chipppppppppp/LIME#78]
### 提案内容

メッセージ取り消し無効時でも、メッセージに返信ができてしまうので
取り消されたメッセージをわかるようにしたい

**Comment by areteruhiro** [comment]
方法がうまいこと、思い浮かばなくて、特定してくれたom5.cクラスの取り消された際の返り値が、一定なのを利用して、以下のコードで一応ログに残すことはできそう、、
使用方法はでresultList に追加された、二個目の値がサーバーidになるので、aSQmanagerでnaver.lineのchat_historyで特定するって方法が一応あります、、、

` 

// 結果を保持するリスト
        List<Object> resultList = new ArrayList<>();

// 最後の値が0であるか
        final boolean[] isLastValueZero = {false};

        hookTarget = lparam.classLoader.loadClass("om5.c");
        XposedHelpers.findAndHookMethod(hookTarget, "u", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Object result = param.getResult();
                
                if (result.toString().matches("[A-Za-z0-9]{33}")) {
                    resultList.add(result);
                    isLastValueZero[0] = false;
                }
         
                else if (result.toString().matches("\\d{18}")) {
                    resultList.add(result);
                    isLastValueZero[0] = false;
                }
                else if (result.equals("0") && resultList.size() == 2 && isLastValueZero[0] == false) {
                    resultList.add(result);

                    
                    StringBuilder sb = new StringBuilder();
                    for (Object obj : resultList) {
                        sb.append(obj.toString()).append(" ");
                    }
                    XposedBridge.log("削除されたメッセージ: " + sb.toString());

                    resultList.clear();
                    isLastValueZero[0] = false;
                }
   
                else {
                    resultList.clear();
                    isLastValueZero[0] = false;
                }
            }
        });`

**Comment by areteruhiro** [comment]
root環境化でいいなら、前回、送らせてもらった、Xposed moduleみたいにSQlite読み取りと同じ要領で、メッセージ特定出来そうだけど、、、

**Comment by areteruhiro** [comment]
asqlite3 naver_line で、チャット履歴を編集できたので、うまいことすれば、チャットに
【送信取り消し済み】って、埋め込めるかもしれないです。
今試してます。

**Comment by areteruhiro** [comment]
data/data/にうまくアクセスできなくて、直接メッセージを書き込むのは断念して、ログに残るようにしました
```
        hookTarget= lparam.classLoader.loadClass("om5.c");
        XposedHelpers.findAndHookMethod(hookTarget, "u", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Object result = param.getResult();

                if (result.toString().matches("[A-Za-z0-9]{33}")) {
                    resultList.add(result);
                    isLastValueZero[0] = false;
                } else if (result.toString().matches("\\d{18}")) {
                    resultList.add(result);
                    savelist.add(result);
                    isLastValueZero[0] = false;
                } else if (result.equals("0") && resultList.size() == 2 && !isLastValueZero[0]) {
                    // 2番目の要素を取得して、serverIdとして使用する
                    Object serverIdObj = resultList.get(1);
                    String serverId = serverIdObj != null ? serverIdObj.toString() : "";

                    // 保存したserverIdを使用してcontentを取得して編集する
                    String content = getContentFromServerId(serverId);
                    if (content != null) {
                        XposedBridge.log("削除されたメッセージ: " + content);
                    }

                    resultList.clear();
                    isLastValueZero[0] = false;
                } else {
                    resultList.clear();
                    isLastValueZero[0] = false;
                }
            }
        });
    }

    // SQLite3コマンドを実行して、server_idに対応するcontentを取得する
    private String getContentFromServerId(String serverId) {
        String command = "su -c sqlite3 /data/data/jp.naver.line.android/databases/naver_line " +
                "\"SELECT content FROM chat_history WHERE server_id='" + serverId + "';\"";
        try {
            return executeSQLite3Command(command);
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            return null;
        }
    }

    // SQLite3コマンドを実行するメソッド
    private String executeSQLite3Command(String command) throws IOException, InterruptedException {
        Process process = Runtime.getRuntime().exec(command);
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        StringBuilder contentBuilder = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            contentBuilder.append(line);
        }
        process.waitFor();
        return contentBuilder.toString();
    }

**Comment by areteruhiro** [comment]
data/dataにアクセス出来る方法あればだれか教えてください、、、

**Comment by areteruhiro** [comment]
sqlite3を利用してます。
端末が対応していない場合は
https://github.com/rojenzaman/sqlite3-magisk-module
などで、sqlite3を導入しなければいけません。

**Comment by areteruhiro** [comment]
アイデアの一つとして、このやり方なので、もう少しいいやり方あれば、、

**Comment by areteruhiro** [comment]
ユーザーネームは、naver_lineのcontactにあるみたいです

**Comment by areteruhiro** [comment]
削除されたトークの名前の取得を可能に
        ```
            // グループの結果を保持するリスト
            List<Object> resultList = new ArrayList<>();
            // 最後の値が0であるかどうかを示すフラグ
            final boolean[] isLastValueZero = {false};
            hookTarget = lparam.classLoader.loadClass("om5.c");
            XposedHelpers.findAndHookMethod(hookTarget, "u", new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {

                    Object result = param.getResult();
                    if (param.getResult().equals("UNSENT")) param.setResult("");

                    if (result.toString().matches("[A-Za-z0-9]{33}")) {
                        resultList.add(result);
                        isLastValueZero[0] = false;
                    } else if (result.toString().matches("\\d{18}")) {
                        resultList.add(result);
                        isLastValueZero[0] = false;
                    } else if (result.equals("0") && resultList.size() == 2 && !isLastValueZero[0]) {
                        // 2番目の要素を取得して、serverIdとして使用する
                        Object serverIdObj = resultList.get(1);
                        String serverId = serverIdObj != null ? serverIdObj.toString() : "";

                        Object talkIdObj = resultList.get(0);
                        String talkId = talkIdObj != null ? talkIdObj.toString() : "";


                        StringBuilder sb = new StringBuilder();
                        for (Object obj : resultList) {
                            sb.append(obj.toString()).append(" ");
                        }
                        // 保存したserverIdを使用してcontentを取得して編集する
                        String content = getContentFromServerId(serverId);

                        //保存したtalkIDを利用してnameを取得する

                        String gruop_name = get_group_name(talkId);
                        String talk_name = talk_name(talkId);

                        if (content != null && (gruop_name != null || talk_name != null)) {
                            XposedBridge.log("削除されたメッセージ: " + sb.toString());
                            XposedBridge.log("削除されたメッセージ: " + (gruop_name != null ? gruop_name : " ") + (talk_name != null ? talk_name : " ") + content);
                        }




                        resultList.clear();
                        isLastValueZero[0] = false;
                    } else {
                        resultList.clear();
                        isLastValueZero[0] = false;
                    }
                }


                // SQLite3コマンドを実行して、server_idに対応するcontentを取得する
                private String getContentFromServerId(String serverId) {
                    String content = null;
                    int retryCount = 10; // リトライの最大回数
                    int retryInterval = 1000; // リトライ間隔（ミリ秒）

                    // リトライ回数分繰り返す
                    for (int i = 0; i < retryCount; i++) {
                        try {
                            String command = "su -c sqlite3 /data/data/jp.naver.line.android/databases/naver_line " +
                                    "\"SELECT content FROM chat_history WHERE server_id='" + serverId + "';\"";
                            content = executeSQLite3Command(command);

                            if (content != null) {
                                break; // contentがnullでない場合はループを抜ける
                            }
                        } catch (IOException | InterruptedException e) {
                            e.printStackTrace();
                        }

                        try {
                            Thread.sleep(retryInterval); // リトライ間隔を待つ
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }

                    return content;
                }


                private String get_group_name(String talkId) {
                    String gruop_name = null;
                    int retryCount = 2; // リトライの最大回数
                    int retryInterval = 100; // リトライ間隔（ミリ秒）

                    // リトライ回数分繰り返す
                    for (int i = 0; i < retryCount; i++) {
                        try {
                            String command = "su -c sqlite3 /data/data/jp.naver.line.android/databases/naver_line " +
                                    "\"SELECT name FROM groups WHERE id='" + talkId + "';\"";
                            gruop_name = executeSQLite3Command(command);

                            if (gruop_name != null) {
                                break; // nameがnullでない場合はループを抜ける
                            }
                        } catch (IOException | InterruptedException e) {
                            e.printStackTrace();
                        }


                        try {
                            Thread.sleep(retryInterval); // リトライ間隔を待つ
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }

                    return gruop_name;
                }

                private String talk_name(String talkId) {
                    String talk_name = null;
                    int retryCount = 2; // リトライの最大回数
                    int retryInterval = 100; // リトライ間隔（ミリ秒）

                    // リトライ回数分繰り返す
                    for (int i = 0; i < retryCount; i++) {
                        try {
                            String command = "su -c sqlite3 /data/data/jp.naver.line.android/databases/naver_line " +
                                    "\"SELECT name FROM contacts WHERE m_id='" + talkId + "';\"";
                            talk_name = executeSQLite3Command(command);

                            if (talk_name != null) {
                                break; // nameがnullでない場合はループを抜ける
                            }
                        } catch (IOException | InterruptedException e) {
                            e.printStackTrace();
                        }


                        try {
                            Thread.sleep(retryInterval); // リトライ間隔を待つ
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        //リトライ回数繰り返してもnullが返ってくる場合
                        //以下のコマンドを実行してtalk_nameを取得する


                    }

                    return talk_name;
                }


                // SQLite3コマンドを実行する
                private String executeSQLite3Command(String command) throws IOException, InterruptedException {
                    try {
                        java.lang.Process process = getRuntime().exec(command);
                        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                        StringBuilder contentBuilder = new StringBuilder();
                        String line;
                        while ((line = reader.readLine()) != null) {
                            contentBuilder.append(line);
                        }
                        process.waitFor();
                        return contentBuilder.toString();
                    } catch (IOException | InterruptedException e) {
                        // エラーが発生した場合はログに出力
                        e.printStackTrace();
                        return null;
                    }
                }
            });
            }

**Comment by areteruhiro** [comment]
画像削除の際、画像とわかるように
スタンプ、動画、ファイル未対応


            List<Object> resultList = new ArrayList<>();
            final boolean[] isLastValueZero = {false};
            hookTarget = lparam.classLoader.loadClass("om5.c");
            XposedHelpers.findAndHookMethod(hookTarget, "u", new XC_MethodHook() {
                        @Override
                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {

                            Object result = param.getResult();
                            if (param.getResult().equals("UNSENT")) param.setResult("");
                            XposedBridge.log("test:" + result);
                            if (result.toString().matches("[A-Za-z0-9]{33}")) {
                                resultList.add(result);
                                isLastValueZero[0] = false;
                            } else if (result.toString().matches("\\d{18}")) {
                                resultList.add(result);
                                isLastValueZero[0] = false;
                            } else if (result.equals("0") && resultList.size() == 2 && !isLastValueZero[0]) {
                                // 2番目の要素を取得して、serverIdとして使用する
                                Object serverIdObj = resultList.get(1);
                                String serverId = serverIdObj != null ? serverIdObj.toString() : "";

                                Object talkIdObj = resultList.get(0);
                                String talkId = talkIdObj != null ? talkIdObj.toString() : "";

                                StringBuilder sb = new StringBuilder();
                                for (Object obj : resultList) {
                                    sb.append(obj.toString()).append(" ");
                                }
                                // 保存したserverIdを使用してcontentを取得して編集する
                                String content = getContentFromServerId(serverId);
                                String gruop_name = get_group_name(talkId);
                                String talk_name = talk_name(talkId);
                                String image_check = image_check(serverId);

                                if ((content != null || image_check != null) && (gruop_name != null || talk_name != null)) {
                                    XposedBridge.log("削除されたメッセージ: " + sb.toString());
                                    XposedBridge.log("削除されたメッセージ: " + (gruop_name != null ? gruop_name : "") + (talk_name != null ? talk_name : "") + ":" + content + image_check);
                                }
                                resultList.clear();
                                isLastValueZero[0] = false;
                            } else {resultList.clear();isLastValueZero[0] = false;}
                        }
                        int retryCount = 1;
                        int retryInterval = 100; 
                        private String getContentFromServerId(String serverId) {
                            String content = null;

                            for (int i = 0; i < retryCount; i++) {
                                try {
                                    String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                                            "\"SELECT content FROM chat_history WHERE server_id='" + serverId + "';\"";
                                    content = executeSQLite3Command(command);

                                    if (content != null) {
                                        break;
                                    }
                                } catch (IOException | InterruptedException e) {
                                    e.printStackTrace();
                                }try {Thread.sleep(retryInterval);
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                            }
                            return content;
                        }
                        private String get_group_name(String talkId) {
                            String gruop_name = null;


                            for (int i = 0; i < retryCount; i++) {
                                try {
                                    String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                                            "\"SELECT name FROM groups WHERE id='" + talkId + "';\"";
                                    gruop_name = executeSQLite3Command(command);

                                    if (gruop_name != null) {
                                        break; 
                                    }
                                } catch (IOException | InterruptedException e) {
                                    e.printStackTrace();
                                }


                                try {
                                    Thread.sleep(retryInterval); 
                                } catch (InterruptedException e) {
                                    e.printStackTrace();

                                }}
                            return gruop_name;
                        }
                        private String talk_name(String talkId) {
                            String talk_name = null;

             
                            for (int i = 0; i < retryCount; i++) {
                                try {
                                    String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                                            "\"SELECT name FROM contacts WHERE m_id='" + talkId + "';\"";
                                    talk_name = executeSQLite3Command(command);

                                    if (talk_name != null) {
                                        break; 
                                    }
                                } catch (IOException | InterruptedException e) {
                                    e.printStackTrace();
                                }


                                try {
                                    Thread.sleep(retryInterval); 
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }

                            }
                            return talk_name;
                        }


                        private String image_check(String serverId) {
                            String image_check = null;

                            for (int i = 0; i < retryCount; i++) {
                                try {
                                    String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                                            "\"SELECT attachement_image FROM chat_history WHERE server_id='" + serverId + "';\"";
                                    image_check = executeSQLite3Command(command);
                                    if ("1".equals(image_check)) {
                                        image_check = "画像が削除されました";
                                        break;
                                    }
                                    if ("0".equals(image_check)) {
                                        image_check = " ";
                                        break;
                                    }


                                } catch (IOException | InterruptedException e) {
                                    e.printStackTrace();
                                }

                                try {
                                    Thread.sleep(retryInterval);
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                            }
                            return  image_check;
                        }


// SQLite3コマンドを実行する
                private String executeSQLite3Command(String command) throws IOException, InterruptedException {
                    try {
                        java.lang.Process process = getRuntime().exec(command);
                        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                        StringBuilder contentBuilder = new StringBuilder();
                        String line;
                        while ((line = reader.readLine()) != null) {
                            contentBuilder.append(line);
                        }
                        process.waitFor();
                        return contentBuilder.toString();
                    } catch (IOException | InterruptedException e) {
                        e.printStackTrace();
                        return null;
                    }
                }
            });
            }

**Comment by Chipppppppppp** [comment]
すみません、忙しくて追えていませんでした
データベースをいじることで新たな道が開けそうですね

**Comment by areteruhiro** [comment]
if (content != null || image_check != null && (gruop_name != null || talk_name != null)) {
  ログ出力この条件ですね、、

**Comment by areteruhiro** [comment]
このコード機能しないですね、、すみません

**Comment by areteruhiro** [comment]
このコード使えませんね、すみません🙇

**Comment by areteruhiro** [comment]
このコード使えないので、非表示にさせていただきます。

**Comment by areteruhiro** [comment]
普通にorg.apache.thrift.n　クラスにしたら良かったんですね
     ```  
       hookTarget = lparam.classLoader.loadClass("org.apache.thrift.n");
        XposedBridge.hookAllMethods(hookTarget, "a", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                String paramValue = param.args[1].toString();

                if (paramValue.contains("type:DUMMY,")) {
                    // param1 と param2 の値を取得
                    String[] parts = paramValue.split(",");
                    String serverId = null;
                    String talkId = null;
                    for (String part : parts) {
                        if (part.trim().startsWith("param1:")) {
                            talkId  = part.trim().substring("param1:".length());

                        } else if (part.trim().startsWith("param2:")) {
                            serverId = part.trim().substring("param2:".length());
                        }
                    }


                        XposedBridge.log("param1: " + serverId);
                        XposedBridge.log("param2: " + talkId);

                        // 保存したserverIdとtalkIdを使用してcontentを取得して編集する
                        String content = getContentFromServerId(serverId);
                        String image_check = image_check(serverId);
                        String gruop_name = get_group_name(talkId);
                        String talk_name = talk_name(talkId);


                        if (content != null && (gruop_name != null || talk_name != null)) {
                            XposedBridge.log("削除されたメッセージ: " + (gruop_name != null ? gruop_name : "") + (talk_name != null ? talk_name : "") + ":" + content + image_check);

                    }

                    }
                }

        });



    }
    int retryCount = 2;
    int retryInterval = 100;
    private String getContentFromServerId(String serverId) {
        String content = null;

        for (int i = 0; i < retryCount; i++) {
            try {
                String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                        "\"SELECT content FROM chat_history WHERE server_id='" + serverId + "';\"";
                content = executeSQLite3Command(command);

                if (content != null) {
                    break;
                }
            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
            }try {Thread.sleep(retryInterval);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        return content;
    }
    private String get_group_name(String talkId) {
        String gruop_name = null;


        for (int i = 0; i < retryCount; i++) {
            try {
                String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                        "\"SELECT name FROM groups WHERE id='" + talkId + "';\"";
                gruop_name = executeSQLite3Command(command);

                if (gruop_name != null) {
                    break;
                }
            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
            }


            try {
                Thread.sleep(retryInterval);
            } catch (InterruptedException e) {
                e.printStackTrace();

            }}
        return gruop_name;
    }
    private String talk_name(String talkId) {
        String talk_name = null;


        for (int i = 0; i < retryCount; i++) {
            try {
                String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                        "\"SELECT name FROM contacts WHERE m_id='" + talkId + "';\"";
                talk_name = executeSQLite3Command(command);

                if (talk_name != null) {
                    break;
                }
            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
            }


            try {
                Thread.sleep(retryInterval);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        }
        return talk_name;
    }


    private String image_check(String serverId) {
        String image_check = null;

        for (int i = 0; i < retryCount; i++) {
            try {
                String command = "su -c sqlite3 /data_mirror/data_ce/null/0/jp.naver.line.android/databases/naver_line " +
                        "\"SELECT attachement_image FROM chat_history WHERE server_id='" + serverId + "';\"";
                image_check = executeSQLite3Command(command);
                if ("1".equals(image_check)) {
                    image_check = "画像が削除されました";
                    break;
                }
                if ("0".equals(image_check)) {
                    image_check = " ";
                    break;
                }


            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
            }

            try {
                Thread.sleep(retryInterval);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        return  image_check;
    }


    // SQLite3コマンドを実行する
    private String executeSQLite3Command(String command) throws IOException, InterruptedException {
        try {
            java.lang.Process process = getRuntime().exec(command);
            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            StringBuilder contentBuilder = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                contentBuilder.append(line);
            }
            process.waitFor();
            return contentBuilder.toString();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            return null;
        }
    }

**Comment by areteruhiro** [comment]
~~一応個人的には、ギリギリ実用的なところまで出来たので、この機能については後は任せます~~

**Comment by Chipppppppppp** [comment]
わかりました。

**Comment by areteruhiro** [comment]
> わかりました。

chathistoryのActivity見てますけど実装難しい感じしますね
Micro-Gみたいに不可能って感じはしないですが、

色々また試してみます
~~リアル優先でお願いします、もう少しで学校も始まるでしょうし。~~

**Comment by Chipppppppppp** [comment]
できたら Pull Request にしてお願いします (完成していなくても Pull Request にして作業したほうがいいかもしれません)

**Comment by areteruhiro** [comment]
> できたら Pull Request にしてお願いします (完成していなくても Pull Request にして作業したほうがいいかもしれません)

わかりました、よろしくお願いします。
