### ISSUE TITLE
[Bug] Letter Sealing暗号化によってトークが見れなくなる問題について

### ISSUE THREAD

**Issue by flar3-shiki** [Chipppppppppp/LIME#88]
### 内容の詳細

環境は、メインがiPhoneのLINE（14.3.1が最新）でサブとしてGalaxy S22 を使用しています。
サブ側は、非root。LSPatchでパッチ適用し Windows版偽装でログインしています。

Letter Sealingの影響でトークの復号化ができないことがあり、該当したトークが以下のような表示になります。
「メッセージを表示できません
このメッセージは未読の状態で、利用していた端末からは移行されなかったため表示できません。」

事象としてはサブAndroid端末を使ってやり取りすると、そこの部分のトークだけ iPhone側では上記のような表示になります。

また、メインiPhoneもサブAndroidもどちらもLINEを使っていない状態が続くと（おそらく30分程度？）
双方ともに上記のエラー表示になり、そのトークは読めなくなってしまいます。

わかる範囲で調べてみたところ、メインがiPhoneでサブがAndroidだと同じ人物とのトークルームであっても
Letter Sealing キーフィンガープリントが変わってしまうのが原因のようです。

別アカウントを使ってメイン・サブ双方ともにAndroidで確認してみたところ、
キーフィンガープリントはメインとLIMEパッチ済みサブでどちらも一致しました。

もしかするとLINE側の仕様かもしれませんが、
Windows PC版の偽装という観点を考えるとやや不可解な挙動なためバグとして報告させていただきます。

### 再現する手順

メインがiPhoneでサブでパッチ済みLINEの状態でトークを行う。

### モジュールのバージョン

1.8.0

### LINEアプリのバージョン

14.3.2

**Comment by Chipppppppppp** [comment]
Android ではやはり問題なく動作しますね
iOS だと発生する問題かもしれません

**Comment by Chipppppppppp** [comment]
スマホ側で Letter Sealing をオフにすると解決できますか?

**Comment by flar3-shiki** [comment]
ありがとうございます。
Letter Sealingは2021年7月頃から事実上の強制適用が始まっていて、オンになっている人はオフにできなくなっているようです。
試してみたところ「セキュリティ保護強化のため...」というポップアップが出てオフにできませんでした。

**Comment by Chipppppppppp** [comment]
強制適用前にオフにしていた人は複数デバイスログインは正しく使えているようです。
iOS ,端末を所持していないため確認できないのですが、iOS で Letter Sealing オンで動いている人も確認しています。(https://twitter.com/catlogle/status/1770652521746579473)
もしかしたらたまたまうまくいかなかっただけで、再度やり直したら行けたりしませんか…?

**Comment by Chipppppppppp** [comment]
コメントによると、すべてのメッセージを既読にした状態で PC 偽装ログインする必要があるとのことです。
また、それでもだめな場合、一度 PC 偽装をしたメッセージが見れない端末でメッセージを送信してから PC 偽装でログインしなおすといけるかもしれないらしいです。

**Comment by flar3-shiki** [comment]
ありがとうございます
今一回だけそちらの方法で行けて、再現可能な形にするため試していますが、
また出来なくなってしまったので、方法がわかりましたらまた書かせていただきますね

**Comment by flar3-shiki** [comment]
私の環境でほぼ確実にメッセージが正常に送受信できる手順がわかりました。（不要な手順がもしかしたらあるかもです）

1. iPhone側のLINEで「設定」→「アカウント」→「ログイン中の端末」に行き、ログアウトできる端末があればすべてログアウトボタンを押す。（操作中のiPhoneはここには出てこない）

2. この時点でiPhone側で任意の個人トークルームに入って、自分のキーフィンガープリント（以下キー）を確認して覚えておく。
（最後の2組くらいをメモっておくのが楽） 

3. LIMEパッチ済みAndroidサブでLINEを開いて所定の手順でログインする。
ただし、必ず「Email and Password」でログインする。（QRコードではダメ）

4. ログイン出来たら誰でもいいので個人トークルームを開いて、双方ともにキーが一致するか確認する。
一致していれば終わり。一致しなければ 5. 以降を行う。

5. キーが一致しない場合は 1. の要領で先ほどログインしたばかりのサブからiPhone側の操作でログアウトする。
6. サブのLINEをマルチタスク画面から終了して再度開く。

7. アカウント情報が云々と出て、画面下部に赤い削除ボタンがあるのでそれを押してデータを削除して、そのまま 3. 以降の手順でログインしなおす。

この手順で端末も変えたりして何回か試しましたが、ほぼ確実にログインできました。

また、3端末以上ではログインできないとのことでしたが サブAndroidでログインし正常動作を確認した後であれば、
Apple WatchとiPadのもう2台ログインしても問題なく動作し、合計4台でトークの送受信ができました。

**Comment by Chipppppppppp** [comment]
OKです
