### ISSUE TITLE
PCとしてログインする

### ISSUE THREAD

**Issue by yucan07** [Chipppppppppp/LIME#92]
### 内容の詳細

非root環境でPCとしてログインする際、LINEアカウントをアメリカの電話番号で作成した場合はエラーが発生し、ログインできない

### 再現する手順

アメリカの電話番号で登録したLINEアカウントを使って、非root環境でPCとしてログインを選択します。ログインする際には、QRコードをスキャンする方法を用います。

### モジュールのバージョン

1.8.1

### LINEアプリのバージョン

14.3.2

**Comment by Chipppppppppp** [comment]
これは確認済みですが、すでに日本のアカウントの場合でも PC としてログインする手法が対策されてしまったため、おそらくほかの手段を使用する必要があります。

**Comment by s1204IT** [comment]
https://github.com/Chipppppppppp/LIME/pull/130#pullrequestreview-2079630771
