### ISSUE TITLE
[Bug] LIME 1.8.1でダークモードを有効化できない

### ISSUE THREAD

**Issue by flar3-shiki** [Chipppppppppp/LIME#93]
### 内容の詳細

度々失礼します。
LIMEを1.8.1にアップデートしたところ、着せ替えが適用出来なくなりました。

デフォルトテーマが見づらいため、「ブラック」テーマを適用しようとすると1.8.1に更新後から一瞬適用されるものの、
「着せ替えを適用できません。再度ダウンロードしてください。」とエラーダイアログが表示され、アプリが再起動しテーマがまたデフォルトの白いテーマに戻ってしまいます。

指示通り再度ダウンロードし直しても適用できません。

LIME 1.8.0では起きていないようです（現在は戻して使っています）

### 再現する手順

LIME 1.8.1を適用した状態で、設定→着せ替え→ダークモードでは「ブラック」着せ替えを適用をオンにする

もしくはマイ着せ替えから、「ブラック」を選択する。

### モジュールのバージョン

1.8.1

### LINEアプリのバージョン

14.3.2

**Comment by areteruhiro** [comment]
2つの方法を提案します。

1:1.8.0のテーマに関する機能を無効化にしてから、ブラックテーマをダウンロードし直す。

2:モジュール設定からLIME適用を外してブラックテーマを適用させて、ブラックテーマになってから、適用させる。

**Comment by Chipppppppppp** [comment]
最も、1.8.1 は 1.8.0 の完全下位互換なのでわざわざ使う必要はないかと思われます。

**Comment by flar3-shiki** [comment]
なるほど、わかりました。
では1.8.0を使います。
