### ISSUE TITLE
Compact stamp/Emoji

### ISSUE THREAD

**Issue by TV-Toshikawa** [Chipppppppppp/LIME#94]
### 提案内容

Add feature to change the size of stamp to size of text/emoji, and disable feature that display the emoji same size as sticker, when there is only 1 emoji and no other text.

**Comment by s1204IT** [comment]
![](https://github.com/Chipppppppppp/LIME/assets/52069677/75e66d09-c6f3-4c35-934f-c045cb415816)

日本語で再度レポートしてください。  
翻訳サイト等を使い無理に英語を使おうとすると、日本語に再翻訳する際に別の意味で翻訳され、意図が異なる内容になってしまう場合があります。  
イキらず普通に日本語で書いてください。
