### ISSUE TITLE
[Bug]: 不具合報告

### ISSUE THREAD

**Issue by Vanagloria417** [Chipppppppppp/LIME#98]
### LSPatch 使用の有無

- [X] 私は LSPatch を使用している状態での報告を行います

### 内容の詳細

非root端末で、PC版に偽装してlineにログインしたところ、アプリを開かないと通知が来ない問題に直面しました。相手からメッセージが来ても、lineアプリを開いていないと通知が来ず、アプリを開くとその瞬間に通知が来ます。使用端末はPixel 7a, アプリのバックグラウンド動作は無制限に設定済みです。

何か不明点、改善報告などごさいましたら【pumu902@uma3.be】までご連絡ください。

### 再現する手順

PC版に偽装してログインし、相手からメッセージを送ってもらいます。(通話の通知は来ます、一般のメッセージの通知だけが来ません)

### 有効にしている LIME の設定

VOOM アイコンを削除, ウォレットアイコンを削除, ニュースまたは通話アイコンを削除, ボトムバーのアイコンを均等に配置, ボトムバーのアイコンのラベルを削除, 広告を削除, おすすめを削除, 送信取り消しを拒否

### バージョンの確認

- [X] 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています

**Comment by Chipppppppppp** [comment]
PC 版の通知が来ない問題は確認済みです。
